#!/usr/bin/env python3
import argparse
import pathlib
import struct
import sys
import zlib


PNG_SIG = b"\x89PNG\r\n\x1a\n"


def paeth(a: int, b: int, c: int) -> int:
    p = a + b - c
    pa = abs(p - a)
    pb = abs(p - b)
    pc = abs(p - c)
    if pa <= pb and pa <= pc:
        return a
    if pb <= pc:
        return b
    return c


def decode_png_rgba(path: pathlib.Path):
    data = path.read_bytes()
    if data[:8] != PNG_SIG:
        raise ValueError(f"{path}: invalid PNG signature")

    pos = 8
    width = None
    height = None
    bit_depth = None
    color_type = None
    interlace = None
    idat = bytearray()

    while pos + 8 <= len(data):
        length = struct.unpack(">I", data[pos:pos + 4])[0]
        ctype = data[pos + 4:pos + 8]
        cdata_start = pos + 8
        cdata_end = cdata_start + length
        cdata = data[cdata_start:cdata_end]
        pos = cdata_end + 4  # skip CRC

        if ctype == b"IHDR":
            width, height, bit_depth, color_type, comp, filt, interlace = struct.unpack(">IIBBBBB", cdata)
            if comp != 0 or filt != 0:
                raise ValueError(f"{path}: unsupported PNG compression/filter method")
        elif ctype == b"IDAT":
            idat.extend(cdata)
        elif ctype == b"IEND":
            break

    if width is None or height is None:
        raise ValueError(f"{path}: missing IHDR")
    if bit_depth != 8 or color_type != 6:
        raise ValueError(f"{path}: only 8-bit RGBA PNG (color type 6) is supported")
    if interlace != 0:
        raise ValueError(f"{path}: interlaced PNG is not supported")

    raw = zlib.decompress(bytes(idat))
    stride = width * 4
    expected = (stride + 1) * height
    if len(raw) != expected:
        raise ValueError(f"{path}: decoded data length mismatch ({len(raw)} != {expected})")

    out = bytearray(width * height * 4)
    prev = bytearray(stride)

    for y in range(height):
        row_start = y * (stride + 1)
        filt = raw[row_start]
        src = raw[row_start + 1:row_start + 1 + stride]
        cur = bytearray(stride)

        for x in range(stride):
            left = cur[x - 4] if x >= 4 else 0
            up = prev[x]
            up_left = prev[x - 4] if x >= 4 else 0
            val = src[x]

            if filt == 0:
                cur[x] = val
            elif filt == 1:
                cur[x] = (val + left) & 0xFF
            elif filt == 2:
                cur[x] = (val + up) & 0xFF
            elif filt == 3:
                cur[x] = (val + ((left + up) >> 1)) & 0xFF
            elif filt == 4:
                cur[x] = (val + paeth(left, up, up_left)) & 0xFF
            else:
                raise ValueError(f"{path}: unsupported filter type {filt}")

        # Convert RGBA -> RBGA to match project RBG convention.
        dst_off = y * stride
        for px in range(0, stride, 4):
            r = cur[px + 0]
            g = cur[px + 1]
            b = cur[px + 2]
            a = cur[px + 3]
            out[dst_off + px + 0] = r
            out[dst_off + px + 1] = b
            out[dst_off + px + 2] = g
            out[dst_off + px + 3] = a

        prev = cur

    return width, height, bytes(out)


def emit_c_array(name: str, blob: bytes) -> str:
    lines = [f"const unsigned char {name}[] = {{"]
    for i in range(0, len(blob), 12):
        chunk = blob[i:i + 12]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Convert RGBA PNG files to C arrays in RBGA byte order")
    parser.add_argument("--output", required=True)
    parser.add_argument("inputs", nargs="+")
    args = parser.parse_args()

    out_path = pathlib.Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    entries = []
    for src in args.inputs:
        p = pathlib.Path(src)
        stem = p.stem.lower().replace("-", "_")
        symbol = f"splash_{stem}"
        width, height, blob = decode_png_rgba(p)
        entries.append((symbol, width, height, blob, p))

    with out_path.open("w", encoding="ascii") as f:
        f.write("/* Auto-generated by tools/png_rgba_to_rbg_c.py */\n")
        f.write("/* Pixel layout is RBGA (R, B, G, A) by design. */\n\n")
        for symbol, width, height, blob, src_path in entries:
            f.write(f"/* Source: {src_path.as_posix()} */\n")
            f.write(f"const unsigned int {symbol}_width = {width}u;\n")
            f.write(f"const unsigned int {symbol}_height = {height}u;\n")
            f.write(emit_c_array(f"{symbol}_rbga", blob))
            f.write("\n\n")

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as e:
        print(f"error: {e}", file=sys.stderr)
        raise
