name: "CI custom (No public release)"

on:
  workflow_dispatch:
    inputs:
      make_args:
        description: pass extra make argumments to Program compilation
      disc_stop_at_boot:
        type: boolean
        description: include DISC_STOP_AT_BOOT=1 in make command
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
    steps:

      - name: Install dependencies
        run: |
          apk add build-base git python3

      - uses: actions/checkout@v6
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --prune --unshallow

      - name: Resolve optional DISC_STOP_AT_BOOT
        run: |
          if [ "${{ github.event.inputs.disc_stop_at_boot }}" = "true" ]; then
            echo "DISC_STOP_ARG=DISC_STOP_AT_BOOT=1" >> $GITHUB_ENV
          else
            echo "DISC_STOP_ARG=" >> $GITHUB_ENV
          fi

      - name: Compile PS2 build
        run: |
          make release COMMIT_HASH=${GITHUB_SHA::7} BINDIR=PS2BBL_CUSTOM_BUILD/ EGSM_BUILD=1 EMBED_PS1VN=1 ${{ github.event.inputs.make_args }} ${{ env.DISC_STOP_ARG }}

      - name: Compile PSX build
        run: |
          make release COMMIT_HASH=${GITHUB_SHA::7} BINDIR=PS2BBL_CUSTOM_BUILD/ PSX=1 EGSM_BUILD=1 EMBED_PS1VN=1 ${{ github.event.inputs.make_args }} ${{ env.DISC_STOP_ARG }}

      - name: list
        run: |
          git ls-files -i --exclude-standard -c

      - name: include logo converter script
        run: |
          cp tools/png_to_logo_rbga.py PS2BBL_CUSTOM_BUILD/png_to_logo_rbga.py

      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v7
        with:
          name: PS2BBL_CUSTOM_BUILD
          path: |
            PS2BBL_CUSTOM_BUILD/*
